#
# LuaDist Travis-CI Hook
#

# Since CMake is not directly supported we use erlang VMs
language: erlang

# Allow luajit to fail
matrix:
  allow_failures:
    - env: LUA="luajit"

# We need CMake and LuaDist
install:
  - sudo apt-get install cmake
  - git submodule update --init

# Use LuaDist to deploy the module
script:
  - ./bootstrap

# Execute additional tests or commands
after_script:
  - ./_install/bin/luadist list

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always